apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hello1
  labels:
    app.kubernetes.io/name: hello1
spec:
  replicas: 4
  selector:
    matchLabels:
      app.kubernetes.io/name: hello1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello1
    spec:
      containers:
        - name: hello-container
          image: busybox
          command: ['sh', '-c', 'echo Hello from my container! && sleep 3600']
